# LOGGING
logging:
  level:
   org.springframework.web: DEBUG

  # APPLICATION
spring:
  application:
   name: turkcell-crm-asset-management
  # MONGODB
  profiles: dev
  data:
    mongodb:
      authentication-database: admin
      database: turkcell-crm
      host: 207.154.232.181
      port: 31233
      username: root
      password: root

---

  # APPLICATION
spring:
  application:
    name: turkcell-crm-asset-management
  profiles: prod
  # MONGODB
  data:
    mongodb:
      authentication-database: admin
      database: turkcell-crm
      host: 165.22.22.133
      port: 31786
      username: root
      password: kafein2020!...
