# LOGGING
logging:
  level:
   org.springframework.web: DEBUG

  # APPLICATION
spring:
  application:
   name: turkcell-crm-asset-management
  # MONGODB
  data:
    mongodb:
#      authentication-database: admin
#      database: turkcell-crm
#      host: localhost
#      port: 27017
#      username: root
#      password: root
       authentication-database: admin
       database: turkcell-crm
       host: 165.22.22.133
       port: 31786
       username: root
       password: kafein2020!...

server:
  port: 8080
  servlet:
    context-path: asset-management